version: "0009--21-Nov-2022"
copyright: "2022"
author: "Sasha Nabila Fortuna"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/cinvetsin/os222"
githubpagelink: "https://cinvetsin.github.io/os222/"
tblink: "https://os.vlsm.org/Log/cinvetsin.tar.bz2.txt"
myloglink: "/TXT/mylog.txt"
encoding: "UTF-8"
github: [metadata]
